import React, {Component} from 'react';

import {
    Accordion,
    AccordionItem,
    AccordionItemHeading,
    AccordionItemButton,
    AccordionItemPanel,
} from 'react-accessible-accordion';

// Demo styles, see 'Styles' section below for some notes on use.
import 'react-accessible-accordion/dist/fancy-example.css';
import './styles/Accordions.sass'

class Accordions extends Component {
    constructor(props) {
        super(props);
    }

    render() {
        return (
            <Accordion className='row' allowMultipleExpanded allowZeroExpanded>
                {
                    Object.entries(this.props.result).map((res, res_ind) => (
                        res[1].length ? <AccordionItem className='col' key={res_ind}>
                            <AccordionItemHeading>
                                <AccordionItemButton className='accordion__button'>
                                    {res[0]}
                                </AccordionItemButton>
                            </AccordionItemHeading>
                            <AccordionItemPanel className='panel-bg-clr'>
                                {
                                    res[1].length > 1 ?
                                        <ul className='margin-text'>
                                            {/*<u className='bg-color'>Variable Sentences:</u>*/}
                                            {res[1].map((vars, ind) =>
                                                <li key={ind}> {vars}</li>
                                            )}
                                        </ul>
                                        :
                                        <p className='margin-text'>
                                            {/*<span className='bg-color'><b>Autogenerated Summary: </b></span>*/}
                                            {res[1]}
                                        </p>
                                }
                            </AccordionItemPanel>
                        </AccordionItem> : null
                    ))
                }
            </Accordion>
        );
    }
}

export default Accordions;