import React, {Component} from 'react';
import SearchBar from './SearchBar'
import './styles/Home.sass'

class Home extends Component {
    constructor(props) {
        super(props);
        this.state = {
            summary: [],
            variable_sentences: [],
            loading: false
        };
        this.getResults = this.getResults.bind(this)
    }

    getResults(id) {
        this.setState({
            summary: [],
            variable_sentences: [],
            loading: true
        })
        let api_endpoint = 'http://193.175.238.92:8000/vadis_app?ssoar_id=' + id;
        let myHeaders = new Headers();
        myHeaders.append("Accept", "application/json");
        // myHeaders.append("auth-key", "zusammen");

        // let requestOptions = {
        //     method: 'GET',
        //     mode: 'no-cors',
        //     // headers: myHeaders,
        //     redirect: 'follow'
        // };
        // fetch(api_endpoint, requestOptions)
        fetch(api_endpoint)
            .then(response => response.json())
            .then(result => {
                this.setState({
                    summary: result['summary'],
                    variable_sentences: result['variable_sentences'],
                    loading: false
                })
            })
            .catch(error => console.log('error', error));
    }

    render() {
        return (
            <div className='row'>
                <div className='d-flex justify-content-center'>
                    <SearchBar placeholder={'Search by id...'} globalSearch getResults={this.getResults}/>
                </div>
                {
                    this.state.summary.length ?
                        <div className='d-flex justify-content-center'>
                            <div className='card'>
                                <p className='margin-text'>
                                    <span
                                        className='text-cadetblue'><b>Autogenerated Summary:</b></span> {this.state.summary}
                                </p>
                                {
                                    this.state.variable_sentences.length ?
                                        <div className='d-flex justify-content-center'>
                                            <ul className='margin-text'><u className='text-cadetblue'>Variable Sentences:</u>
                                                {this.state.variable_sentences.map((vars, ind) =>
                                                    <li key={ind}> {vars}</li>
                                                )}
                                            </ul>
                                        </div>
                                        : null
                                }
                            </div>
                        </div>
                        :
                        this.state.loading ?
                            <div className="d-flex justify-content-center">
                                <div className="spinner-border text-cadetblue" role="status">
                                    {/*<span className="sr-only">Loading...</span>*/}
                                </div>
                            </div>
                            :
                            null
                }
            </div>

        );
    }
}

export default Home;
