import React, {Component} from "react";
import ShowMoreText from "react-show-more-text";
import './styles/Table.sass'

class Table extends Component {
    constructor(props) {
        super(props);

        this.state = {
            input: null,
            button_id: null,
        };
        this.handleClick = this.handleClick.bind(this)
    }

    handleClick(id, ind) {
        this.setState({
            button_id: ind
        })
        this.props.getVariableResults(id, ind)
    }

    render() {
        return <table className="table table-hover">
            <tbody>
            {this.props.ssoar_docs.map((doc, ind) => (
                <tr key={ind}>
                    <td className='row'>
                        <h6 className='col-10'>{doc['_source']['title']}</h6>
                        <a className='col-2 text-end link-clr'
                           href={doc['_source']['pdf']}
                           target='_blank'
                           rel='noreferrer'>Go to source!</a>
                        <div className='col-12 small-txt align-txt'>
                            <ShowMoreText width={0} lines={2} anchorClass='show-more-less-clickable link-clr'>
                                {doc['_source']['abstract']}
                            </ShowMoreText>
                        </div>
                        <div className='d-flex justify-content-center'>
                            <button type="button" className="btn btn-link clr-cadetblue" id={ind}
                                    onClick={() => this.handleClick(doc['_id'].split('-')[2], ind)}>Get Variables Data!
                            </button>
                        </div>
                        {
                            'result' in this.props.vadis_data[ind] ?
                                'summary' in this.props.vadis_data[ind]['result'] && this.props.vadis_data[ind]['result']['summary'].length ?
                                    <div className='d-flex justify-content-center'>
                                        <div className='card'>
                                            <p className='margin-text'>
                                    <span
                                        className='clr-cadetblue'><b>Autogenerated Summary:</b></span> {this.props.vadis_data[ind]['result']['summary']}
                                            </p>
                                            {
                                                'variable_sentences' in this.props.vadis_data[ind]['result'] && this.props.vadis_data[ind]['result']['variable_sentences'].length ?
                                                    <div className='d-flex justify-content-center'>
                                                        <ul className='margin-text'><u className='clr-cadetblue'>Variable
                                                            Sentences:</u>
                                                            {this.props.vadis_data[ind]['result']['variable_sentences'].map((vars, ind) =>
                                                                <li key={ind}> {vars}</li>
                                                            )}
                                                        </ul>
                                                    </div>
                                                    : null
                                            }
                                        </div>
                                    </div>
                                    :
                                    null
                                :
                                this.props.loading && this.state.button_id === ind ?
                                    <div className="d-flex justify-content-center">
                                        <div className="spinner-border clr-cadetblue" role="status">
                                            {/*<span className="sr-only">Loading...</span>*/}
                                        </div>
                                    </div>
                                    :
                                    null
                        }
                    </td>
                </tr>
            ))}
            </tbody>
        </table>
    }
}

export default Table;