import React, {Component} from "react";
import ShowMoreText from "react-show-more-text";
import './styles/Table.sass'
import Accordions from "./Accordions";
import {Tooltip as ReactTooltip} from "react-tooltip";

class Table extends Component {
    constructor(props) {
        super(props);

        this.state = {
            input: null,
            button_id: null,
        };
        this.handleClick = this.handleClick.bind(this)
    }

    handleClick(id, ind) {
        this.setState({
            button_id: ind
        })
        this.props.getParams(id)
    }

    render() {
        return <table className="table table-striped table-hover">
            <tbody>
            {this.props.ssoar_docs.map((doc, ind) => (
                <tr key={ind}>
                    <td className='row'>
                        <div className='col-11'>
                            <h6>
                                <u className='bg-color' onClick={() => this.handleClick(doc['_id'].split('-')[2], ind)}>
                                    {doc['_source']['title']}
                                    &nbsp;&nbsp; <span className="fw-lighter">[{doc['_id']}]</span>
                                </u>
                                {'date_info' in doc['_source'] && 'issue_date' in doc['_source']['date_info'] ?
                                    <span id={'date_info' + ind} className="err-color fw-normal" key='src_journal'>
                                    <i> ({doc['_source']['date_info']['issue_date']}) </i>
                                </span> : 'dates' in doc['_source'] && 'issue_date' in doc['_source']['dates'] ?
                                        <span className="err-color fw-normal" key='src_journal'>
                                        <i> ({doc['_source']['dates']['issue_date']}) </i>
                                    </span> : null}
                            </h6>
                        </div>
                        <div className='col-1 text-end bg-color'>
                            {'url' in doc['_source'] ?
                                <a
                                    href={doc['_source']['url']}
                                    target='_blank'
                                    rel='noreferrer'>[source]
                                </a>
                                :
                                null
                            }
                        </div>

                        {'vadis_data' in doc ?
                            <>
                                {
                                    'summary' in doc['vadis_data'] ?
                                        <div className='col-12 small-txt align-txt'>
                                            <span id={'summary' + ind}>{doc['vadis_data']['summary']}</span>
                                            <ReactTooltip anchorId={'summary' + ind}
                                                          place="top"
                                                          variant="info"
                                                          float={true}
                                                          content="Autogenerated Summary"/>
                                            {'language' in doc['_source'] && doc['_source']['language'] ?
                                                <><span id={'language' + ind} className='err-color'
                                                        key='src_journal'>
                                                        <i> ({doc['_source']['language']}) </i>
                                                </span>
                                                    <ReactTooltip anchorId={'language' + ind}
                                                                  place="top"
                                                                  variant="info"
                                                                  float={true}
                                                                  content="Document Language"/></>
                                                : null}
                                        </div>
                                        : null
                                }
                            </> : null
                        }
                            <div className='col-10 small-txt err-color'>
                                {'authors' in doc['_source'] ? doc['_source']['authors'].map((author, i) => (
                                    <>
                                        <span id={'author' + i + ind} className="fw-normal" key={i}>
                                            <i> &#x2022; {'name' in author ? author['name'] : author['name_string']} </i>
                                        </span>
                                        <ReactTooltip anchorId={'author' + i + ind}
                                                      place="top"
                                                      variant="info"
                                                      float={true}
                                                      content="Author"/>
                                    </>
                                )) : null}
                            </div>
                        {
                            'variable_sentences' in doc['vadis_data'] ?
                                <div className='col-2 text-end'>
                                        <span id={'sentences' + ind} className='my-badge small-txt'>
                                            Linked Variables: {Object.keys(doc['vadis_data']['variable_sentences']).length}
                                        </span>
                                    <ReactTooltip anchorId={'sentences' + ind}
                                                  place="top"
                                                  variant="info"
                                                  float={true}
                                                  content="Count"/>
                                </div> : null
                        }

                        {'source' in doc['_source'] && 'src_journal' in doc['_source']['source'] ?
                            <div className='col-12 small-txt err-color'>
                                <span className="fw-light" key='src_journal'>
                                    <i id={'source' + ind}> {doc['_source']['source']['src_journal']} </i>
                                    <ReactTooltip anchorId={'source' + ind}
                                                  place="top"
                                                  variant="info"
                                                  float={true}
                                                  content="Source"/>
                                </span>
                            </div> : null}

                        {'abstract' in doc['_source'] && doc['_source']['abstract'] ?
                            <>
                                <div id={'abstract' + ind} className='col-12 small-txt align-txt'>
                                    <ShowMoreText width={0} lines={this.props.detailedView ? 0 : 3}
                                                  anchorClass='show-more-less-clickable bg-color'>
                                        <span>{doc['_source']['abstract']}</span>
                                    </ShowMoreText>
                                </div>
                                <ReactTooltip anchorId={'abstract' + ind}
                                              place="top"
                                              variant="info"
                                              float={true}
                                              content="Author's Abstract"/>
                            </>
                            : null
                        }
                        {
                            this.props.detailedView ?
                                this.props.loading ?
                                    <div className="d-flex justify-content-center">
                                        <div className="spinner-border bg-color" role="status">
                                            {/*<span className="sr-only">Loading...</span>*/}
                                        </div>
                                    </div>
                                    : 'vadis_data' in doc && !('error' in doc['vadis_data']) ?
                                        <Accordions result={doc['vadis_data']}/>
                                        : <div className='d-flex justify-content-center'>
                                            <span className='err-color'>
                                                Something Went Wrong!
                                            </span>
                                        </div>
                                : null
                        }
                    </td>
                </tr>
            ))}
            </tbody>
        </table>;
    }
}

export default Table;